### PR TITLE
Micrortps qurt sitl fixes rebase

### PR DESCRIPTION
**Pull request by mcharleb**

### CODE REVIEW

**Comment by mcharleb** [comment]
@VicenteEprosima I removed generate_microRTPS_UDP_bridge.py

**Comment by mcharleb** [comment]
@VicenteEprosima There are build issues... resolving. Don't merge yet

**Comment by vicentemonge** [comment]
@mcharleb this files are not needed:
msg/templates/uorb/microRTPS_UDP_client.cpp.template
src/modules/rtps_udp/UDP_node.cxx
src/modules/rtps_udp/UDP_node.h

And src/modules/rtps_udp/CMakeLists.txt is needed to be moved to the new module src/micrortps_bridge

**Comment by mcharleb** [comment]
@VicenteEprosima This should be working now. I had to disable the dir tree removal and the generation of the client CMakeLists.txt file since it is not being used and it kept overwriting the lop level project file.

**Comment by vicentemonge** [comment]
@mcharleb Thanks for your work!

**Pull request merged**
