### PR TITLE
Simplified the documentations

### PR DESCRIPTION
**Pull request by vilhjalmur89**
Simplified the README to make it easier to understand. 

Changed the 'Hello World' example to create a third node that communicates through FastRTPS, instead of modifying the generated bridge.

Let me know if you have any comments.

### CODE REVIEW

**Comment by vicentemonge** [comment]
Hi @vilhjalmur89,

We have a pull request over [devguide](https://github.com/PX4/Devguide/pull/219) too with the documentation your are reviewed, and this is already reviewed by @hamishwillee. Do you want this changes over the other documentation?

Thanks.

**Comment by vilhjalmur89** [comment]
Aha, let's stick to the Devguide PR then.

**Comment by hamishwillee** [comment]
@vilhjalmur89 @VicenteEprosima 
1. When the devguide PR is done, we probably want to replace this documentation with a link to the "official" version. Duplication is not a good thing.
2. @vilhjalmur89 There is more review to be done on the devguide PR for this. Just waiting on @VicenteEprosima to confirm when their initial work is complete. At that point I'll do a cleanup, and would really appreciate your further review.

**Comment by vilhjalmur89** [comment]
@hamishwillee In that case, you might want to look over my changes before you do a cleanup, to avoid duplicate work. But I'll comment on the devguide-PR once it has been updated.

**Pull request closed without merging**
