### PR TITLE
Add autogenerated micrortps UDP bridge in modules/rtps_udp

### PR DESCRIPTION
**Pull request by mcharleb**
PX4 will no longer build if lib/micro-CDR is not in the module list.

This PR adds a code generator for the UDP bridge for the uORB topics specified in the build config file in cmake/configs/{target}.cmake

Support for posix_sttl_default and posix_eagle_* was added.

Signed-off-by: Mark Charlebois <charlebm@gmail.com>

### CODE REVIEW

**Comment by mcharleb** [comment]
This PR adds a code generator for the UDP bridge for the uORB topics specified in the build config file in cmake/configs/{target}.cmake

**Comment by vicentemonge** [comment]
Hi Mark,

First at all, thanks for the work!

I think with the new changes in the code since the pull request creation some things could be changed. The generate_microRTPS_UDP_bridge.py and microRTPS_UDP_client.cpp.template don't needed as we add this functionality to the original ones without UDP surname. You only need to add the new parameters to the original generate script if you need more than is recently introduced.

The other changes looks great, we'll be waiting for the update of the PR.


Thanks!

**Review by vicentemonge — CHANGES_REQUESTED** [review]
Hi Mark,

First at all, thanks for the work!

I think with the new changes in the code since the pull request creation some things could be changed. The generate_microRTPS_UDP_bridge.py and microRTPS_UDP_client.cpp.template don't needed as we add this functionality to the original ones without UDP surname. You only need to add the new parameters to the original generate script if you need more than is recently introduced.

The other changes looks great, we'll be waiting for the update of the PR.

Thanks!

**Comment by mcharleb** [comment]
@VicenteEprosima Replaced by https://github.com/eProsima/Firmware/pull/15

**Pull request closed without merging**
